#!/bin/bash

set -e

# Set up a virtual environment with Go Botany inside.

cd $(dirname ${BASH_SOURCE[0]})

./utils/check-dependencies

rm -rf ./venv

python3.9 -m venv --system-site-packages --upgrade-deps ./venv

# Install a dependency for Haystack, setuptools_scm, because
# setuptools_scm is not detected properly if installed along with
# the other the packages. Also, setuptools_scm requires a recent
# version of setuptools.
./venv/bin/pip install setuptools==50.3.2
./venv/bin/pip install setuptools_scm==4.1.2

# Install the rest of the packages.

./venv/bin/pip install -e ..
./venv/bin/pip install coverage
./venv/bin/pip install selenium
