#!/bin/bash

set -e

# Set up a virtual environment with Go Botany inside.

cd $(dirname ${BASH_SOURCE[0]})

./utils/check-dependencies

rm -rf ./venv

# This assumes the latest system Python version is the one to use.
# (If another is needed, can change to something like python39, etc.)
python -m venv --system-site-packages ./venv

# Upgrade pip.
./venv/bin/pip install --upgrade pip

# Install a dependency for Haystack, setuptools_scm, because
# setuptools_scm is not detected properly if installed along with
# the other the packages. Also, setuptools_scm requires a recent
# version of setuptools.
./venv/bin/pip install setuptools==50.3.2
./venv/bin/pip install setuptools_scm==4.1.2

# Install the rest of the packages.

./venv/bin/pip install -e ..
./venv/bin/pip install coverage
./venv/bin/pip install selenium
