#!/bin/bash

# Start Solr running as a background process on the local machine,
# possibly after downloading it to a nearby directory.

set -e

DEV=$(dirname "${BASH_SOURCE[0]}")
cd $DEV

EXAMPLE=usr/solr-4.7.2/example

if [ ! -d $EXAMPLE ]
then
    cd usr
    curl -OL http://archive.apache.org/dist/lucene/solr/4.7.2/solr-4.7.2.tgz
    tar xzf solr-4.7.2.tgz
    cd ..
fi

echo 'Installing Solr XML schema'

./django build_solr_schema > $EXAMPLE/solr/collection1/conf/schema.xml

echo 'Running Solr in the background'

cd $EXAMPLE
rm -f nohup.out
nohup java -jar start.jar "$@" > output.log 2>&1 &
