pile_suffixes = {
    u'Carex': 'ca',
    u'Composites': 'co',
    u'Equisetaceae': 'eq',
    u'Lycophytes': 'ly',
    u'Monilophytes': 'mo',
    u'Non-Orchid Monocots': 'nm',
    u'Non-Thalloid Aquatic': 'ap',
    u'Orchid Monocots': 'om',
    u'Poaceae': 'po',
    u'Remaining Graminoids': 'rg',
    u'Remaining Non-Monocots': 'rn',
    u'Alternate Remaining Non-Monocots': 'an',
    u'Non-Alternate Remaining Non-Monocots': 'nn',
    u'Thalloid Aquatic': 'ta',
    u'Woody Angiosperms': 'wa',
    u'Woody Gymnosperms': 'wg',
    }
