# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantshare', '0002_auto_20160413_1915'),
    ]

    operations = [
        #migrations.AlterUniqueTogether(
        #    name='emailaddress',
        #    unique_together=set([]),
        #),
        #migrations.RemoveField(
        #    model_name='emailaddress',
        #    name='user',
        #),
        #migrations.RemoveField(
        #    model_name='emailconfirmation',
        #    name='email_address',
        #),
        #migrations.DeleteModel(
        #    name='EmailAddress',
        #),
        #migrations.DeleteModel(
        #    name='EmailConfirmation',
        #),
    ]
