# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-12-16 14:14
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations
import gobotany.plantshare.models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('plantshare', '0005_auto_20180519_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenedimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(storage=django.core.files.storage.FileSystemStorage(base_url=b'/media/upload_images/', location=b'/Users/john/Documents/dev/newfs/gobotany-app/gobotany/media/upload_images'), upload_to=gobotany.plantshare.models.rename_image_by_type),
        ),
    ]
