# Generated by Django 3.0.14 on 2021-05-21 10:55

import django.core.files.storage
from django.db import migrations, models
import gobotany.plantshare.models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('plantshare', '0006_auto_20181216_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenedimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/upload_images/', location='/Users/john/Documents/dev/newfs/gobotany-app/gobotany/media/upload_images'), upload_to=gobotany.plantshare.models.rename_image_by_type),
        ),
        migrations.AlterField(
            model_name='screenedimage',
            name='image_type',
            field=models.CharField(blank=True, choices=[('AVATAR', 'User Avatar'), ('SIGHTING', 'Sighting Photo'), ('CHECKLIST', 'Checklist Photo'), ('QUESTION', 'Question Photo')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Everyone: public'), ('USERS', 'All PlantShare users'), ('PRIVATE', 'Only you and PlantShare staff')], default='PUBLIC', max_length=7),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='details_visibility',
            field=models.CharField(choices=[('USERS', 'All PlantShare users'), ('PRIVATE', 'Only you and PlantShare staff')], default='USERS', max_length=7),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location_visibility',
            field=models.CharField(choices=[('USERS', 'All PlantShare users'), ('PRIVATE', 'Only you and PlantShare staff')], default='USERS', max_length=7),
        ),
    ]
