# Generated by Django 4.1 on 2024-09-27 00:21

import django.core.files.storage
from django.db import migrations
import gobotany.plantshare.models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('plantshare', '0008_alter_screenedimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenedimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/upload_images/', location='/Users/john/Documents/dev/newfs/gobotany-app/gobotany/media/upload_images'), upload_to=gobotany.plantshare.models.rename_image_by_type),
        ),
    ]
