# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 18:47
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('plantoftheday', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='plantoftheday',
            managers=[
                ('get_by_date', django.db.models.manager.Manager()),
            ],
        ),
    ]
