#!/bin/bash

PYTHON=${1:-python2.7}

# Make sure that the system has provided requirements that we would
# rather not have to build for ourselves.

if ! $PYTHON -c 'import lxml.etree' 2>/dev/null
then
    cat <<EOF

Error: The "lxml" library needs to be installed in your system Python.

       Ubuntu Linux:        sudo apt-get install python-lxml
       OS X with MacPorts:  sudo port install py27-lxml

EOF
    exit 1
fi

if [ "$(uname -s)" == "Darwin" ] && ! $PYTHON -c 'import psycopg2' 2>/dev/null
then
    cat <<EOF

Error: The "psycopg" library needs to be installed in your system Python.

       OS X with MacPorts:  sudo port install py27-psycopg2

EOF
    exit 1
fi

if [ "$(uname -s)" == "Darwin" ] && ! $PYTHON -c 'import pylibmc' 2>/dev/null
then
    cat <<EOF

Error: The "pylibmc" library needs to be installed in your system Python.

       OS X with MacPorts:  sudo port install py27-pylibmc

EOF
    exit 1
fi

if [ "$(uname -s)" == "Linux" ] &&
    ! echo '#include <postgresql/utils/errcodes.h>' |cc -E - >/dev/null 2>&1 &&
    ! echo '#include <postgresql/server/utils/errcodes.h>' |cc -E - >/dev/null 2>&1
then
    cat <<EOF

Error: The "libpq" library headers need to be installed on your system.

       Ubuntu Linux:        sudo apt-get install libpq-dev

EOF
    exit 1
fi

if [ "$(uname -s)" == "Linux" ] &&
    ! echo '#include <libmemcached/memcached.h>' |cc -E - >/dev/null 2>&1
then
    cat <<EOF

Error: The "libmemcached" library headers need to be installed on your system.

       Ubuntu Linux:        sudo apt-get install libmemcached-dev

EOF
    exit 1
fi
