#!/bin/bash

PYTHON=${1:-python3.11}

# Make sure that the system has provided requirements that we would
# rather not have to build for ourselves.

if ! $PYTHON -c 'import lxml.etree' 2>/dev/null
then
    cat <<EOF

Error: The "lxml" library needs to be installed in your system Python.

       Ubuntu Linux:        sudo apt-get install python-lxml
       Mac OS with MacPorts:  sudo port install py311-lxml

EOF
    exit 1
fi

if [ "$(uname -s)" == "Darwin" ] && ! $PYTHON -c 'import psycopg2' 2>/dev/null
then
    cat <<EOF

Error: The "psycopg" library needs to be installed in your system Python.

       Mac OS with MacPorts:  sudo port install py311-psycopg2

       Note: if errors importing psycopg2 in Python shell, may have
       to install port postgresq13 (see import error output)

EOF
    exit 1
fi

if [ "$(uname -s)" == "Darwin" ] && ! $PYTHON -c 'import pylibmc' 2>/dev/null
then
    cat <<EOF

Error: The "pylibmc" library needs to be installed in your system Python.

       Mac OS with MacPorts:  sudo port install py38-pylibmc
       (port search pylibmc showed no later py*- version available)

       or:

       pip install pylibmc==1.6.2

       Doing the latter gets a newer version of pylibmc (MacPorts
       has 1.6.1)

       Note: if errors importing pylibmc in Python shell, may have
       to install port libmemcached (see import error output)

EOF
    exit 1
fi

if [ "$(uname -s)" == "Darwin" ] && ! $PYTHON -c 'import magic' 2>/dev/null
then
    cat <<EOF

Error: The "libmagic" library needs to be installed on your system.

       Mac OS with MacPorts:  sudo port install py-magic

EOF
    exit 1
fi

if [ "$(uname -s)" == "Linux" ] &&
    ! echo '#include <postgresql/utils/errcodes.h>' |cc -E - >/dev/null 2>&1 &&
    ! echo '#include <postgresql/server/utils/errcodes.h>' |cc -E - >/dev/null 2>&1
then
    cat <<EOF

Error: The "libpq" library headers need to be installed on your system.

       Ubuntu Linux:        sudo apt-get install libpq-dev

EOF
    exit 1
fi

if [ "$(uname -s)" == "Linux" ] &&
    ! echo '#include <libmemcached/memcached.h>' |cc -E - >/dev/null 2>&1
then
    cat <<EOF

Error: The "libmemcached" library headers need to be installed on your system.

       Ubuntu Linux:        sudo apt-get install libmemcached-dev

EOF
    exit 1
fi
