# Generated by Django 3.0.14 on 2021-05-23 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0004_document_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='added_at',
            new_name='last_uploaded_at',
        ),
    ]
