# Generated by Django 3.0.14 on 2021-05-23 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0005_auto_20210523_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='last_uploaded_at',
            new_name='last_updated_at',
        ),
    ]
