# Generated by Django 3.2.25 on 2024-08-11 14:32

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0008_alter_document_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='upload',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/docs/', location='/Users/john/Documents/dev/newfs/gobotany-app/gobotany/media/docs'), upload_to=''),
        ),
    ]
