# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dkey', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='illustrativespecies',
            options={'verbose_name_plural': 'Illustrative species'},
        ),
        migrations.AlterField(
            model_name='lead',
            name='goto_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='goto_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leadins', to='dkey.Page'),
        ),
    ]
