# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-12-16 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dkey', '0002_auto_20170717_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dkey.Lead'),
        ),
    ]
