# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-31 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dkey', '0003_auto_20181216_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hybrid',
            name='number1',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='hybrid',
            name='number2',
            field=models.IntegerField(blank=True),
        ),
    ]
