# Generated by Django 3.0.14 on 2021-05-21 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dkey', '0005_auto_20190131_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='goto_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leadins', to='dkey.Page'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='dkey.Lead'),
        ),
    ]
