# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-09 11:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170717_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcecitation',
            name='publication_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2018)], verbose_name='Publication Year'),
        ),
    ]
