# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-12-16 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181216_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='description',
            field=models.TextField(),
        ),
    ]
