# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-12-16 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20181216_0918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='update',
            options={'ordering': ['-date']},
        ),
    ]
