# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-31 18:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20181216_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='species_name',
            field=models.CharField(blank=True, db_index=True, default=b'', help_text=b'Automatically populated from scientific_name', max_length=60),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='subspecific_epithet',
            field=models.CharField(blank=True, db_index=True, default=b'', help_text=b'Automatically populated from scientific_name', max_length=60),
        ),
        migrations.AlterField(
            model_name='sourcecitation',
            name='publication_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2019)], verbose_name='Publication Year'),
        ),
    ]
