# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-17 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190131_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
