# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-16 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_highlight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distribution',
            options={'ordering': ('scientific_name', 'state', 'county'), 'verbose_name': 'Distribution record'},
        ),
        migrations.AddField(
            model_name='update',
            name='family',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
