# Generated by Django 3.0.14 on 2021-05-21 10:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import gobotany.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190816_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='character-value-images'),
        ),
        migrations.AlterField(
            model_name='character',
            name='unit',
            field=models.CharField(blank=True, choices=[('mm', 'Millimeters'), ('cm', 'Centimeters'), ('m', 'Meters')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='charactervalue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='character-value-images'),
        ),
        migrations.AlterField(
            model_name='conservationstatus',
            name='region',
            field=models.CharField(choices=[('CT', 'Connecticut'), ('ME', 'Maine'), ('MA', 'Massachusetts'), ('NH', 'New Hampshire'), ('RI', 'Rhode Island'), ('VT', 'Vermont')], max_length=80),
        ),
        migrations.AlterField(
            model_name='contentimage',
            name='image',
            field=models.ImageField(help_text='Image will be renamed and moved based on other field information.', max_length=300, upload_to=gobotany.core.models._content_image_path, verbose_name='content image'),
        ),
        migrations.AlterField(
            model_name='contentimage',
            name='image_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ImageType', verbose_name='image type'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='species_name',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Automatically populated from scientific_name', max_length=60),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='subspecific_epithet',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Automatically populated from scientific_name', max_length=60),
        ),
        migrations.AlterField(
            model_name='glossaryterm',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='glossary-images'),
        ),
        migrations.AlterField(
            model_name='invasivestatus',
            name='region',
            field=models.CharField(choices=[('ct', 'Connecticut'), ('ma', 'Massachusetts'), ('me', 'Maine'), ('nh', 'New Hampshire'), ('ri', 'Rhode Island'), ('vt', 'Vermont')], max_length=80),
        ),
        migrations.AlterField(
            model_name='sourcecitation',
            name='publication_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2021)], verbose_name='Publication Year'),
        ),
    ]
