# Generated by Django 3.0.14 on 2021-06-03 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210521_0655'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Highlight',
        ),
        migrations.DeleteModel(
            name='Update',
        ),
    ]
