# Generated by Django 3.1.14 on 2022-04-09 00:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210602_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invasivestatus',
            name='invasive_in_region',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='invasivestatus',
            name='prohibited_from_sale',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='sourcecitation',
            name='publication_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2022)], verbose_name='Publication Year'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='north_american_introduced',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='north_american_native',
            field=models.BooleanField(null=True),
        ),
    ]
