# Generated by Django 3.2.25 on 2024-08-11 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20220408_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentimage',
            name='object_id',
            field=models.PositiveIntegerField(help_text='Usually a Taxon id; refers to Content Type'),
        ),
        migrations.AlterField(
            model_name='sourcecitation',
            name='publication_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2024)], verbose_name='Publication Year'),
        ),
    ]
