# Generated by Django 4.1.13 on 2026-08-06 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20240811_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcecitation',
            name='publication_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2026)], verbose_name='Publication Year'),
        ),
    ]
